#!/bin/sh
set -e

# Building curl is required because libauthretry (from "make test") requires
# libcurl.
#
# It might be possible to patch the makefile to have libauthretry link against
# the system's installed libcurl, patches welcome.
#
# gnutls tests run against the built curl and libcurl rather than the installed
# one as we don't ship a curl linked against gnutls (only gnutls libraries).

export DEB_BUILD_PROFILES="pkg.curl.gnutls-only"
export VERBOSE=1

echo "dh_update_autotools_config"
dh_update_autotools_config

echo "dh_autoreconf"
dh_autoreconf

echo "debian/rules override_dh_auto_configure "
debian/rules override_dh_auto_configure

echo "debian/rules override_dh_auto_build"
debian/rules override_dh_auto_build

echo "debian/rules override_dh_auto_test"
debian/rules override_dh_auto_test
